DELETE FROM recycling_info;
INSERT INTO recycling_info (id, material, disposal_method) VALUES
                                        (1, 'Kunststoff','Gelber Sack oder Gelbe Tonne'),
                                        (2, 'Glas','Glascontainer'),
                                        (3, 'Karton','Altpapiercontainer oder Papiertonne'),
                                        (4, 'Tüte','Gelber Sack oder Gelbe Tonne'),
                                        (5, 'en:Paperboard', 'Altpapiercontainer oder Papiertonne'),
                                        (6, 'Flasche','Glascontainer'),
                                        (7, 'Papier','Altpapiercontainer oder Papiertonne'),
                                        (8, 'Dose','Altmetallcontainer'),
                                        (9, 'Metall','Gelber Sack oder Gelbe Tonne'),
                                        (10, 'Wiederverwertbare Metalle',' Wertstoffhof oder Altmetallcontainer'),
                                        (11, 'Aluminium','Altmetallcontainer'),
                                        (12, 'Folie','Gelber Sack oder Gelbe Tonne'),
                                        (13, 'Kanne', 'Gelber Sack oder Gelbe Tonne'),
                                        (14, 'en:Tetra Pak', 'Gelber Sack oder Gelbe Tonne'),
                                        (15, 'Kasten', 'Altstoffsammelzentrum'),
                                        (16, 'Konserve','Altmetallcontainer'),
                                        (17, 'Tablettverpackung','Gelber Sack oder Gelbe Tonne'),
                                        (18, 'Ungewellte Pappe','Altpapiercontainer oder Papiertonne'),
                                        (19, 'Deckel','Gelber Sack oder Gelbe Tonne'),
                                        (20, 'Stahl','Altmetallcontainer oder Altstoffsammelzentrum'),
                                        (21, 'Klarglas','Glascontainer'),
                                        (22, 'Etikett','Restmülltonne'),
                                        (23, 'Krug',' Glascontainer'),
                                        (24, 'Frisch','Bioabfalltonne oder Kompost'),
                                        (25, 'Tube','Gelber Sack oder Gelbe Tonne'),
                                        (26, 'Konservendose','Gelber Sack oder Gelbe Tonne'),
                                        (27, 'Ziegel','Altstoffsammelzentrum (Bauschutt)'),
                                        (28, 'Tiefgekühlt','Restmülltonne'),
                                        (29, 'PP 5 Polypropylen','Gelber Sack oder Gelbe Tonne'),
                                        (30, 'Netz','Gelber Sack oder Gelbe Tonne'),
                                        (31, 'Papier und Pappe/Kunststoff/Aluminium','Altpapiercontainer oder Papiertonne/Gelber Sack oder Gelbe Tonne'),
                                        (32, 'en:Bottle or vial', 'Gelber Sack oder Gelbe Tonne'),
                                        (33, 'Schutzatmosphäre',' Gelber Sack oder Gelbe Tonne'),
                                        (34, 'Verbundwerkstoff',' Gelber Sack oder Gelbe Tonne'),
                                        (35, 'en:Sleeve', 'Gelber Sack oder Gelbe Tonne'),
                                        (36, 'en:Vial', 'Gelber Sack oder Gelbe Tonne'),
                                        (37, 'FSC Karton','Altpapiercontainer oder Papiertonne'),
                                        (38, 'Packung','Restmülltonne'),
                                        (39, 'Holz','Altstoffsammelzentrum (Sperrmüll)'),
                                        (40, 'en:Vacuum-packed', 'Gelber Sack oder Gelbe Tonne'),
                                        (41, 'Getränkedose','Altmetallcontainer'),
                                        (42, 'en:Wrapper','Gelber Sack oder Gelbe Tonne'),
                                        (43, 'en:Pouch flask', 'Gelber Sack oder Gelbe Tonne'),
                                        (44, 'PET 1 Polyethylenterephtalat','Gelber Sack oder Gelbe Tonne'),
                                        (45, 'Grünglas','Glascontainer'),
                                        (46, 'en:Bottle cap', 'Gelber Sack oder Gelbe Tonne'),
                                        (47, 'Verpackung','Restmülltonne'),
                                        (48, 'Braunglas','Glascontainer'),
                                        (49, 'Papier und Pappe/Kunststoff','Altpapiercontainer oder Papiertonne/Gelber Sack oder Gelbe Tonne'),
                                        (50, 'Recyceln', 'Wertstoffsammelzentrum'),
                                        (51, 'Einzeltüten','Gelber Sack oder Gelbe Tonne'),
                                        (52, 'Weißblech','Altmetallcontainer'),
                                        (53, 'Schüssel','Gelber Sack oder Gelbe Tonne'),
                                        (54, 'PE 7 Polyethylen','Gelber Sack oder Gelbe Tonne'),
                                        (55, 'en:Lid or cap', 'Gelber Sack oder Gelbe Tonne'),
                                        (56, 'en:Tetra Brik Aseptic', 'Gelber Sack oder Gelbe Tonne'),
                                        (57, 'xx:Cellophane', 'Gelber Sack oder Gelbe Tonne'),
                                        (58, 'en:Wine cork', 'Restmülltonne'),
                                        (59, 'en:Elopak', 'Gelber Sack oder Gelbe Tonne'),
                                        (60, 'en:Capsule', 'Gelber Sack oder Gelbe Tonne'),
                                        (61, 'en:Squeeze bottle', 'Gelber Sack oder Gelbe Tonne'),
                                        (62, 'Glas/Weißblech','Glascontainer/Altmetallcontainer'),
                                        (63, 'Weißblech','Altmetallcontainer oder Altstoffsammelzentrum'),
                                        (64, 'en:Blister','Gelber Sack oder Gelbe Tonne'),
                                        (65, 'Dichtung','Gelber Sack oder Gelbe Tonne'),
                                        (66, 'Wiederverwertetes Material', 'Gelber Sack oder Gelbe Tonne'),
                                        (67, 'O 7 - Andere Kunststoffe','Gelber Sack oder Gelbe Tonne'),
                                        (68, 'Return to store', 'Im Geschäft zurückgeben'),
                                        (69, 'eimer','Gelber Sack oder Gelbe Tonne'),
                                        (70, 'Wiederverwertbares Material', 'Gelber Sack oder Gelbe Tonne'),
                                        (71, 'Getrocknet','Restmülltonne'),
                                        (72, 'Kunststoff/Aluminium','Gelber Sack oder Gelbe Tonne'),
                                        (73, 'HDPE 2 Polyethylen hoher Dichte','Gelber Sack oder Gelbe Tonne'),
                                        (74, 'eierkarton','Altpapiercontainer oder Papiertonne'),
                                        (75, 'en:Envelope', 'Altpapiercontainer oder Papiertonne'),
                                        (76, 'Wiederverwerteter Kunststoff','Gelber Sack oder Gelbe Tonne'),
                                        (77, 'xx:81 C/PAP', 'Altpapiercontainer oder Papiertonne'),
                                        (78, 'Papier und Pappe/Aluminium', 'Altpapiercontainer oder Papiertonne/Altmetallcontainer'),
                                        (79, 'en:Card', 'Altpapiercontainer oder Papiertonne'),
                                        (80, 'en:Fastener', 'Gelber Sack oder Gelbe Tonne'),
                                        (81, 'RPET - Wiederverwertetes PET', 'Gelber Sack oder Gelbe Tonne'),
                                        (82, 'xx:82 C/PAP', 'Altpapiercontainer oder Papiertonne'),
                                        (83, 'en:Return PET bottle to store', 'Im Geschäft zurückgeben'),
                                        (84, 'PS 6 - Polystyrol', 'Gelber Sack oder Gelbe Tonne'),
                                        (85, 'Kunststoff/Weißblech', 'Gelber Sack oder Gelbe Tonne/Altmetallcontainer'),
                                        (86, 'en:Pure-Pak', 'Gelber Sack oder Gelbe Tonne'),
                                        (87, 'Unbekannt', 'Tut uns leid, wir wissen nicht wie du das entsorgen kannst'),
                                        (88, 'en:Tetra Top', 'Gelber Sack oder Gelbe Tonne'),
                                        (89, 'Wachs', 'Restmülltonne'),
                                        (90, 'en:Recycle in glass bin', 'Glascontainer'),
                                        (91, 'Recycelte Pappe', 'Altpapiercontainer oder Papiertonne'),
                                        (92, 'braunglas', 'Glascontainer'),
                                        (93, 'en:Tetra Brik', 'Gelber Sack oder Gelbe Tonne'),
                                        (94, 'pl:szkło', 'Glascontainer'),
                                        (95, 'en:Terrine pot', 'Gelber Sack oder Gelbe Tonne'),
                                        (96, 'pl:słoik', 'Glascontainer'),
                                        (97, 'Essensutensilien', 'Gelber Sack oder Gelbe Tonne'),
                                        (98, 'Kork', 'Restmülltonne'),
                                        (99, 'en:Jug', 'Glascontainer'),
                                        (100, 'en:Tumbler', 'Glascontainer'),
                                        (101, 'en:Sheet', 'Altpapiercontainer oder Papiertonne'),
                                        (102, 'Keramik', 'Restmülltonne oder Alststoffsammelzentrum'),
                                        (103, 'ru:стекло', 'Glascontainer'),
                                        (104, 'xx:90 C/LDPE', 'Gelber Sack oder Gelbe Tonne'),
                                        (105, 'en:Stick', 'Restmülltonne'),
                                        (106, 'en:Individual dose', 'Altmetallcontainer'),
                                        (107, 'Löffel', 'Gelber Sack oder Gelbe Tonne'),
                                        (108, 'en:Pure-Pak Classic', 'Gelber Sack oder Gelbe Tonne'),
                                        (109, 'kunststoff-aluminium', 'Gelber Sack oder Gelbe Tonne'),
                                        (110, 'Sprühdose', 'Altmetallcontainer'),
                                        (111, 'PET - Transparentes', 'Gelber Sack oder Gelbe Tonne'),
                                        (112, 'Leichtes Aluminium', 'Gelber Sack oder Gelbe Tonne'),
                                        (113, 'sprühdose', 'Altmetallcontainer'),
                                        (114, 'PA - Polyamide', 'Gelber Sack oder Gelbe Tonne'),
                                        (115, 'EVOH - Ethylen-Vinylalkohol-Copolymer', 'Gelber Sack oder Gelbe Tonne'),
                                        (116, 'en:canister', 'Gelber Sack oder Gelbe Tonne'),
                                        (117, 'en:Pure-Pak Sense', 'Gelber Sack oder Gelbe Tonne'),
                                        (118, 'en:Dish', 'Gelber Sack oder Gelbe Tonne'),
                                        (119, 'en:Tetra Rex', 'Gelber Sack oder Gelbe Tonne'),
                                        (120, 'en:Small brick', 'Altstoffsammelzentrum (Bauschutt)'),
                                        (121, 'OPP - Orientiertes Polypropylen', 'Gelber Sack oder Gelbe Tonne'),
                                        (122, 'Wellpappe', 'Altpapiercontainer oder Papiertonne'),
                                        (123, 'cs:sklo', 'Glascontainer'),
                                        (124, 'xx:85 C/PAP', 'Gelber Sack oder Gelbe Tonne'),
                                        (125, 'bg:хартия', 'Altpapiercontainer oder Papiertonne'),
                                        (126, 'Baumwolle', 'Restmülltonne'),
                                        (127, 'sl:steklo', 'Glascontainer'),
                                        (128, 'Stoff', 'Restmülltonne'),
                                        (129, 'en:Tie', 'Gelber Sack oder Gelbe Tonne'),
                                        (130, 'Biologisch abbaubarer Kunststoff', 'Gelber Sack oder Gelbe Tonne'),
                                        (131, 'Dunkles Sortierglas', 'Glascontainer'),
                                        (132, 'fi:lasi', 'Glascontainer'),
                                        (133, 'Ohne Verpackung', 'Nichts zu entsorgen'),
                                        (134, 'en:Mixed plastics', 'Gelber Sack oder Gelbe Tonne'),
                                        (135, 'Wiederverwenden', 'Gelber Sack oder Gelbe Tonne'),
                                        (136, 'Stütze', 'Gelber Sack oder Gelbe Tonne'),
                                        (137, 'bg:пластмаса', 'Gelber Sack oder Gelbe Tonne'),
                                        (138, 'Kunststoffklebeband', 'Gelber Sack oder Gelbe Tonne'),
                                        (139, 'PVC 3 - Polyvinylchlorid', 'Gelber Sack oder Gelbe Tonne'),
                                        (140, 'fi:pahvi', 'Altpapiercontainer oder Papiertonne/Gelber Sack oder Gelbe Tonne'),
                                        (141, 'pl:butelka', 'Gelber Sack oder Gelbe Tonne'),
                                        (142, 'fr:Agrafe', 'Gelber Sack oder Gelbe Tonne'),
                                        (143, 'bg:картон', 'Altpapiercontainer oder Papiertonne'),
                                        (144, 'nl:knijpfles', 'Gelber Sack oder Gelbe Tonne'),
                                        (145, 'Gruppierungspaket', 'Gelber Sack oder Gelbe Tonne'),
                                        (146, 'fr:bac-de-tri', 'Gelber Sack oder Gelbe Tonne'),
                                        (147, 'en:Cartridge', 'Altstoffsammelzentrum'),
                                        (148, 'Sprühflasche', 'Altmetallcontainer'),
                                        (149, 'en:Recycle with plastics', 'Gelber Sack oder Gelbe Tonne'),
                                        (150, 'en:Bag-in-box', 'Altpapiercontainer oder Papiertonne/Gelber Sack oder Gelbe Tonne'),
                                        (151, 'Recyceltes Papier', 'Altpapiercontainer oder Papiertonne'),
                                        (152, 'Steige', 'Leergutautomat'),
                                        (153, 'en:Tetra Prisma Aseptic', 'Gelber Sack oder Gelbe Tonne'),
                                        (154, 'stoff', 'Restmülltonne'),
                                        (155, 'en:Jug or canister', 'Gelber Sack oder Gelbe Tonne'),
                                        (156, 'Helles Sortierglas', 'Glascontainer'),
                                        (157, 'Glas/Kunststoff', 'Glascontainer'),
                                        (158, 'PLA - Polylactid', 'Gelber Sack oder Gelbe Tonne'),
                                        (159, 'es:madera', 'Altstoffsammelzentrum (Sperrmüll)'),
                                        (160, 'Wegwerfen', 'Gelber Sack oder Gelbe Tonne'),
                                        (161, 'xx:82 C/ALU', 'Gelber Sack oder Gelbe Tonne'),
                                        (162, 'pl:papier', 'Altpapiercontainer oder Papiertonne'),
                                        (163, 'en:evoh-ethylene-vinyl-alcohol', 'Gelber Sack oder Gelbe Tonne'),
                                        (164, 'xx:90 C/PET', 'Gelber Sack oder Gelbe Tonne'),
                                        (165, 'glas-kunststoff', 'Glascontainer'),
                                        (166, 'en:Case', 'Gelber Sack oder Gelbe Tonne'),
                                        (167, 'xx:90 C/CPP', 'Gelber Sack oder Gelbe Tonne'),
                                        (168, 'Ungefroren', 'Restmülltonne'),
                                        (169, 'Gabel', 'Gelber Sack oder Gelbe Tonne'),
                                        (170, 'xx:81 C/PET', 'Gelber Sack oder Gelbe Tonne'),
                                        (171, 'Glas/Aluminium', 'Glascontainer'),
                                        (172, 'fr:cellulose', 'Altpapiercontainer oder Papiertonne'),
                                        (173, 'Kraftpapier', 'Altpapiercontainer oder Papiertonne'),
                                        (174, 'fsc-papier', 'Altpapiercontainer oder Papiertonne'),
                                        (175, 'el:γυαλί', 'Glascontainer'),
                                        (176, 'en:Tea bag', 'Restmülltonne'),
                                        (177, 'en:Plate', 'Gelber Sack oder Gelbe Tonne'),
                                        (178, 'en:Tethered cap', 'Gelber Sack oder Gelbe Tonne'),
                                        (179, 'fr:papier-sulfurise', 'Altpapiercontainer oder Papiertonne'),
                                        (180, 'nl:drankkarton', 'Gelber Sack oder Gelbe Tonne'),
                                        (181, 'en:String', 'Restmülltonne'),
                                        (182, 'Glas/verschiedene Metalle', 'Glascontainer/Gelber Sack oder Gelbe Tonne'),
                                        (183, 'pizzakarton', 'Altpapiercontainer oder Papiertonne'),
                                        (184, 'sv:plast', 'Gelber Sack oder Gelbe Tonne'),
                                        (185, 'Gold gemischt/Glas mit Gold hinterlegt', 'Glascontainer'),
                                        (186, 'es:aluminio', 'Altmetallcontainer'),
                                        (187, 'en:SIG Combibloc', 'Gelber Sack oder Gelbe Tonne'),
                                        (188, 'Klebeband', 'Gelber Sack oder Gelbe Tonne'),
                                        (189, 'sprühflasche', 'Altmetallcontainer'),
                                        (190, 'Kunststoff/verschiedene Metalle', 'Gelber Sack oder Gelbe Tonne/Altmetallcontainer'),
                                        (191, 'Pizzakarton', 'Altpapiercontainer oder Papiertonne'),
										(192, 'verpackung', 'Gelber Sack oder Gelbe Tonne'),
                                        (193, 'PP 5 - Polypropylen', 'Gelber Sack oder Gelbe Tonne'),
                                        (194, 'PET 1 - Polyethylenterephtalat','Gelber Sack oder Gelbe Tonne');

